name: Deploy APP

env:
  IMAGE_NAME: sureshgkhyd/springboot-flyway-dbmigration
  DOCKERFILE: Dockerfile.caprover
  CAPROVER_APP: springboot-caprover-deployment
  CAPROVER_HOST: https://captain.cr.fullstackdev.tk
  DOCKER_REGISTRY: docker.io

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  publish-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          echo "IMAGE_NAME_WITH_REGISTRY=$DOCKER_REGISTRY/$IMAGE_NAME" >> $GITHUB_ENV
          export IMAGE_NAME_WITH_REGISTRY=$DOCKER_REGISTRY/$IMAGE_NAME
          echo "FULL_IMAGE_NAME=$IMAGE_NAME_WITH_REGISTRY:$GITHUB_SHA-gitsha" >> $GITHUB_ENV
      - name: Login to Docker Hub
        uses:  docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and Push Release to DockerHub
        shell: bash
        run: ./build_and_push.sh
      - name: Deploy to CapRover
        uses: floms/action-caprover@v1
        with:
          host: ${{ env.CAPROVER_HOST }}
          app: ${{ env.CAPROVER_APP }}
          password: "${{ secrets.APP_TOKEN }}"
          image: "${{ env.FULL_IMAGE_NAME }}"